# fly.toml file generated for polished-thunder-589 on 2023-03-15T13:11:16+01:00

app = "polished-thunder-589"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5004
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 5004
